package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

filegroup(
    name = "test_data",
    srcs = glob(["**"]),
)

filegroup(
    name = "benchmark_unittest_data",
    srcs = [
        "dataset/abalone.csv",
        "dataset/adult.csv",
        "dataset/iris.csv",
        "dataset/sim_pte_test.csv",
        "dataset/sim_pte_train.csv",
    ],
)
