# Learner bindings for PYDF
load("//devtools/python/bazel:pytype.bzl", "py_binary")

package(licenses = ["notice"])

# Binary
# =========

py_binary(
    name = "main",
    srcs = ["main.py"],
    deps = [
        # absl:app dep,
        # absl/flags dep,
        # absl/logging dep,
        # ydf dep,
    ],
)
