/*
 * Copyright 2022 Google LLC.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "yggdrasil_decision_forests/utils/blob_sequence.h"

#include <string>

#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include "absl/log/check.h"
#include "absl/status/status.h"
#include "absl/strings/substitute.h"
#include "yggdrasil_decision_forests/utils/filesystem.h"
#include "yggdrasil_decision_forests/utils/test.h"
#include "yggdrasil_decision_forests/utils/testing_macros.h"

namespace yggdrasil_decision_forests {
namespace utils {
namespace blob_sequence {
namespace {

TEST(BlobSequence, BlockSize) {
  EXPECT_EQ(sizeof(internal::FileHeader), 8);
  EXPECT_EQ(sizeof(internal::RecordHeader), 4);
}

SIMPLE_PARAMETERIZED_TEST(BlobSequence_Base, Compression,
                          {Compression::kNone, Compression::kGZIP}) {
  auto path = file::JoinPath(test::TmpDirectory(), "blob_sequence.bin");

  // Create a BS with three blobs.
  ASSERT_OK_AND_ASSIGN(auto output_stream, file::OpenOutputFile(path));
  ASSERT_OK_AND_ASSIGN(
      auto writer, blob_sequence::Writer::Create(output_stream.get(),
                                                 /*compression=*/GetParam()));
  CHECK_OK(writer.Write("HELLO"));
  CHECK_OK(writer.Write(""));  // Empty blob.
  CHECK_OK(writer.Write("WORLD"));
  CHECK_OK(writer.Close());
  CHECK_OK(output_stream->Close());

  // Read the two blobs.
  ASSERT_OK_AND_ASSIGN(auto input_stream, file::OpenInputFile(path));
  ASSERT_OK_AND_ASSIGN(auto reader,
                       blob_sequence::Reader::Create(input_stream.get()));
  std::string blob;
  CHECK(reader.Read(&blob).value());
  CHECK_EQ(blob, "HELLO");
  CHECK(reader.Read(&blob).value());
  CHECK_EQ(blob, "");
  CHECK(reader.Read(&blob).value());
  CHECK_EQ(blob, "WORLD");
  CHECK(!reader.Read(&blob).value());
  CHECK_OK(reader.Close());
  CHECK_OK(input_stream->Close());
}

// Make sure old blog sequence files generated by the BlobSequence_Base test can
// still be read.
SIMPLE_PARAMETERIZED_TEST(BlobSequence_BackwardCompatibility, std::string,
                          {"v0", "v1", "v1_gzip"}) {
  auto path =
      file::JoinPath(test::DataRootDirectory(),
                     absl::Substitute("yggdrasil_decision_forests/"
                                      "test_data/other/blob_sequence_$0.bin",
                                      GetParam()));

  // Read the two blobs.
  ASSERT_OK_AND_ASSIGN(auto input_stream, file::OpenInputFile(path));
  ASSERT_OK_AND_ASSIGN(auto reader,
                       blob_sequence::Reader::Create(input_stream.get()));
  std::string blob;
  CHECK(reader.Read(&blob).value());
  CHECK_EQ(blob, "HELLO");
  CHECK(reader.Read(&blob).value());
  CHECK_EQ(blob, "");
  CHECK(reader.Read(&blob).value());
  CHECK_EQ(blob, "WORLD");
  CHECK(!reader.Read(&blob).value());
  CHECK_OK(reader.Close());
  CHECK_OK(input_stream->Close());
}

TEST(BlobSequence, NotABs) {
  auto path = file::JoinPath(test::TmpDirectory(), "blob_sequence.bin");

  // Create a random text file (not a BS file).
  ASSERT_OK_AND_ASSIGN(auto output_stream, file::OpenOutputFile(path));
  CHECK_OK(output_stream->Write("HELLO WORLD"));
  CHECK_OK(output_stream->Close());

  // Try to read the file.
  ASSERT_OK_AND_ASSIGN(auto input_stream, file::OpenInputFile(path));
  EXPECT_THAT(blob_sequence::Reader::Create(input_stream.get()).status(),
              test::StatusIs(absl::StatusCode::kInvalidArgument));
  CHECK_OK(input_stream->Close());
}

}  // namespace
}  // namespace blob_sequence
}  // namespace utils
}  // namespace yggdrasil_decision_forests
