# Learner bindings for PYDF
# pytype binary only

package(licenses = ["notice"])

# Binary
# =========

py_binary(
    name = "main",
    srcs = ["main.py"],
    python_version = "PY3",
    deps = [
        # absl:app dep,
        # absl/flags dep,
        # absl/logging dep,
        # ydf dep,
    ],
)
