package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

package_group(
    name = "users",
    packages = [
        "//yggdrasil_decision_forests/port/javascript/...",
    ],
)
