package(
    default_visibility = ["//yggdrasil_decision_forests/port/javascript:users"],
    licenses = ["notice"],
)

package_group(
    name = "users",
    packages = [
        "//learning/lib/ami/simple_ml/ports/javascript/...",
        "//yggdrasil_decision_forests/port/javascript/...",
    ],
)
