# Bazel workspace configuration for Yggdrasil Decision Forest Python.
# For Yggdrasil Decision Forest C++, see ../../WORKSPACE.

workspace(name = "ydf")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    strip_prefix = "rules_python-1.6.0",
    url = "https://github.com/bazel-contrib/rules_python/releases/download/1.6.0/rules_python-1.6.0.tar.gz",
)

# This workspace (YDF Python) relies on YDF C++ located at "../../../"
local_repository(
    name = "ydf_cc",
    path = "../../../",
)

load("//:library.bzl", ydf_load_deps = "load_dependencies")

ydf_load_deps()

# Load the dependencies of YDF.
load("@ydf_cc//yggdrasil_decision_forests:library.bzl", ydf_cc_load_deps = "load_dependencies")

ydf_cc_load_deps(repo_name = "@ydf_cc")

# Note: GRPC import several other libraries:
# https://github.com/grpc/grpc/blob/master/bazel/grpc_deps.bzl
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()

# TODO: Enbable CUDA build in OSS
# load("@rules_cuda//cuda:repositories.bzl", "register_detected_cuda_toolchains", "rules_cuda_dependencies")
# rules_cuda_dependencies()
# register_detected_cuda_toolchains()
