load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Yggdrasil Decision Forests

http_archive(
    name = "ydf",
    urls = ["https://github.com/google/yggdrasil-decision-forests/archive/refs/heads/main.zip"],
    strip_prefix = "yggdrasil-decision-forests-main",
)

# Yggdrasil can also be included from an on-disk copy:
# local_repository(
# name = "ydf",
# path = "../../",
# )

# Load the dependencies of YDF.
load("@ydf//yggdrasil_decision_forests:library.bzl", ydf_load_deps = "load_dependencies")
ydf_load_deps(repo_name = "@ydf", exclude_repo="tensorflow")

# Load the dependencies of YDF that cannot be loaded above.
load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")
protobuf_deps()
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()
